name: generate animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate github-contribution-grid-snake.svg
        id: generate_snake
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: makt96
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Debugging step to check the output
      - name: Debug outputs
        run: |
          echo "Generated files:"
          ls dist
          if [ -f dist/github-contribution-grid-snake.svg ]; then
            echo "github-contribution-grid-snake.svg exists"
          else
            echo "github-contribution-grid-snake.svg does not exist"
          fi
          if [ -f dist/github-contribution-grid-snake-dark.svg ]; then
            echo "github-contribution-grid-snake-dark.svg exists"
          else
            echo "github-contribution-grid-snake-dark.svg does not exist"
          fi

      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
